[project]
name = "dataset"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.5.0",
    "huggingface-hub>=1.4.0",
    "openai>=2.17.0",
    "python-dotenv>=1.2.1",
    "tqdm>=4.67.0",
]
